{
 "title": "Compaction",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "GRPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "grpc: started Compact/s",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(grpc_server_started_total{grpc_method=\"Compact\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "grpc: handled Compact/s",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "rate(grpc_server_handled_total{grpc_type=\"unary\", grpc_method=\"Compact\"}[1m]) > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "grpc: Compact latency p90",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, rate(grpc_server_handling_seconds_bucket{grpc_method=\"Compact\"}[1m])) > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "MVCC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "mvcc: current and compacted revision",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "etcd_debugging_mvcc_current_revision",
     "legendFormat": "{{instance}}: {{__name__}}"
    },
    {
     "expr": "etcd_debugging_mvcc_compact_revision",
     "legendFormat": "{{instance}}: {{__name__}}"
    }
   ]
  },
  {
   "title": "mvcc: compacted keys/s",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "rate(etcd_debugging_mvcc_db_compaction_keys_total[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "mvcc: compaction duration p90",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(etcd_debugging_mvcc_db_compaction_total_duration_milliseconds_bucket[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "mvcc: db compaction pause p90",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(etcd_debugging_mvcc_db_compaction_pause_duration_milliseconds_bucket[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "mvcc: index compaction pause p90",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(etcd_debugging_mvcc_index_compaction_pause_duration_milliseconds_bucket[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Bbolt DB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "bbolt: db size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "etcd_mvcc_db_total_size_in_bytes",
     "legendFormat": "{{instance}}: {{__name__}}"
    },
    {
     "expr": "etcd_mvcc_db_total_size_in_use_in_bytes",
     "legendFormat": "{{instance}}: {{__name__}}"
    }
   ]
  }
 ]
}