{
 "title": "Peers",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "peer: rtt p99",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(etcd_network_peer_round_trip_time_seconds_bucket[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "raft: heartbeat failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(etcd_server_heartbeat_send_failures_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "peer: received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(etcd_network_peer_sent_bytes_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "peer: sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "rate(etcd_network_peer_sent_bytes_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "peer: sent failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "rate(etcd_network_peer_sent_failures_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}