{
 "title": "Peers",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Raft", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "raft: proposals committed/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(etcd_server_proposals_committed_total[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "raft: leader changes/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(etcd_server_leader_changes_seen_total[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "raft: heartbeat failures/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(etcd_server_heartbeat_send_failures_total[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Peer Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "peer: rtt p99",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(etcd_network_peer_round_trip_time_seconds_bucket[1m]))",
     "legendFormat": "From: {{instance}} -> To: {{To}}"
    }
   ]
  },
  {
   "title": "peer: sent bytes/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(etcd_network_peer_sent_bytes_total[1m])",
     "legendFormat": "From: {{instance}} -> To: {{To}}"
    }
   ]
  },
  {
   "title": "peer: received bytes/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(etcd_network_peer_received_bytes_total[1m])",
     "legendFormat": "From: {{From}} -> To: {{instance}}"
    }
   ]
  },
  {
   "title": "peer: sent failures/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "rate(etcd_network_peer_sent_failures_total[1m])",
     "legendFormat": "From: {{instance}} -> To: {{To}}"
    }
   ]
  }
 ]
}