{
 "title": "Put",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "grpc: started puts",
   "type": "timeseries",
   "description": "https://sourcegraph.com/github.com/etcd-io/etcd@release-3.5/-/blob/server/etcdserver/api/v3rpc/grpc.go?L89",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "grpc_server_started_total{grpc_type=\"unary\", grpc_method=\"Put\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "server: proposals pending",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    { "expr": "etcd_server_proposals_pending", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "disk: wal write bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "etcd_disk_wal_write_bytes_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "disk: wal fsync duration p99",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(etcd_disk_wal_fsync_duration_seconds_bucket[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "disk: wal fsync count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "etcd_disk_wal_fsync_duration_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "server: proposals committed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "etcd_server_proposals_committed_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mvcc: puts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "targets": [
    { "expr": "etcd_mvcc_put_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "disk: backend commits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "etcd_disk_backend_commit_duration_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "disk: backend commit p90",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(etcd_disk_backend_commit_duration_seconds_bucket[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "server: proposals applied",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "etcd_server_proposals_applied_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "server: proposals failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "etcd_server_proposals_failed_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}