{
 "title": "Puts",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "grpc: started puts",
   "type": "timeseries",
   "description": "https://sourcegraph.com/github.com/etcd-io/etcd@release-3.5/-/blob/server/etcdserver/api/v3rpc/grpc.go?L89",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(grpc_server_started_total{grpc_type=\"unary\", grpc_method=\"Put\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "grpc: handled puts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(grpc_server_handled_total{grpc_type=\"unary\", grpc_method=\"Put\"}[1m]) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "grpc: puts latency p90",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, rate(grpc_server_handling_seconds_bucket{grpc_method=\"Put\"}[5m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "server: proposals pending",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "targets": [
    { "expr": "etcd_server_proposals_pending", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "server: proposals applied",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "rate(etcd_server_proposals_applied_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "server: proposals committed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "rate(etcd_server_proposals_committed_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "server: proposals failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "rate(etcd_server_proposals_failed_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "disk: wal write bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "rate(etcd_disk_wal_write_bytes_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "disk: wal fsync duration p99",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(etcd_disk_wal_fsync_duration_seconds_bucket[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "disk: wal fsync count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "rate(etcd_disk_wal_fsync_duration_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mvcc: puts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 85 },
   "targets": [
    { "expr": "rate(etcd_mvcc_put_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "disk: backend commits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 93 },
   "targets": [
    {
     "expr": "rate(etcd_disk_backend_commit_duration_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "disk: backend commit p90",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 101 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(etcd_disk_backend_commit_duration_seconds_bucket[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}