{
 "title": "Ranges",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "GRPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "grpc: started ranges/s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(grpc_server_started_total{grpc_type=\"unary\", grpc_method=\"Range\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "grpc: handled ranges/s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(grpc_server_handled_total{grpc_method=\"Range\"}[1m]) > 0",
     "legendFormat": "{{instance}}: {{grpc_code}}"
    }
   ]
  },
  {
   "title": "grpc: sent bytes/s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_sent_bytes_total[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Etcdserver", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "server: slow read index/s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "rate(etcd_server_slow_read_indexes_total[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "server: read index failed/s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "rate(etcd_server_read_indexes_failed_total[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "MVCC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "mvcc: ranges total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "rate(etcd_mvcc_range_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}